const express = require('express');
const cors = require('cors');
require('dotenv').config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/', (req, res) => res.json({ message: 'LuxEdu API is running', version: '1.0.0' }));
app.use('/api/auth', require('./routes/auth'));
app.use('/api/students', require('./routes/students'));
app.use('/api/classes', require('./routes/classes'));
app.use('/api/attendance', require('./routes/attendance'));
app.use('/api/grades', require('./routes/grades'));
app.use('/api/payments', require('./routes/payments'));
app.use('/api/bulletin', require('./routes/bulletin'));
app.use('/api/whatsapp', require('./routes/whatsapp'));
app.use('/api/certificat', require('./routes/certificat'));
module.exports = app;
