const express = require('express');
const router = express.Router();
const { getPayments, createPayment, markPaid, sendPaymentRemindersAuto } = require('../controllers/paymentController');
const { protect } = require('../middleware/auth');
router.use(protect);
router.get('/', getPayments);
router.post('/', createPayment);
router.put('/:id/pay', markPaid);
router.post('/reminders', sendPaymentRemindersAuto);
module.exports = router;
